<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <UserSecretsId>1bf630dc-c41a-43fd-9aee-c027d6ea4fe6</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebAppProjectDependenciesLibrary\WebAppProjectDependenciesLibrary.csproj" />
  </ItemGroup>

</Project>
