version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
      dotnet: 8.x
    commands:
      # Find and delete the global.json files that were added by CodeBuild. This causes issues when multiple SDKs are installed.
      - find / -type f -name 'global.json' -delete
      # The tests need .NET 6, 8 and 10. .NET6 is installed by default. .NET8 is added in the runtime-versions. .NET 10 is installed manually.
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 10.0
  pre_build:
    commands:
      - export DOTNET_CLI_TELEMETRY_OPTOUT=1

  build:
    commands:
      - dotnet build AWS.Deploy.sln -c Release
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover AWS.Deploy.sln -c Release --no-build --logger trx --logger "console;verbosity=detailed" --results-directory ./testresults

  post_build:
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d #v3
        
reports:
    aws-dotnet-deploy-tests:
        file-format: VisualStudioTrx
        files:
            - '**/*'
        base-directory: './testresults'
