version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
      dotnet: 8.x
  pre_build:
    commands:
      - export DOTNET_CLI_TELEMETRY_OPTOUT=1

  build:
    commands:
      - dotnet build AWS.Deploy.sln -c Release
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover AWS.Deploy.sln -c Release --no-build --logger trx --logger "console;verbosity=detailed" --results-directory ./testresults

  post_build:
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d #v3
        
reports:
    aws-dotnet-deploy-tests:
        file-format: VisualStudioTrx
        files:
            - '**/*'
        base-directory: './testresults'
