version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      # install .NET SDK
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 6.0
      - export PATH="$PATH:$HOME/.dotnet"
  pre_build:
    commands:
      - export DOTNET_CLI_TELEMETRY_OPTOUT=1

  build:
    commands:
      - dotnet build AWS.Deploy.sln -c Release
      - dotnet test AWS.Deploy.sln -c Release --no-build --logger trx --results-directory ./testresults
reports:
    aws-dotnet-deploy-tests:
        file-format: VisualStudioTrx
        files:
            - '**/*'
        base-directory: './testresults'
