style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/aws/aws-dotnet-deploy
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - docs
        - style
        - refactor
        - perf
        - test
        - build
        - ci
        - chore
    sort_by: Subject
  commit_groups:
    sort_by: Custom
    title_order:
      - feat
      - fix
      - docs
      - style
      - refactor
      - perf
      - test
      - build
      - ci
      - chore
    title_maps:
      feat: Features
      fix: Bug Fixes
      docs: Documentation
      style: Style
      refactor: Code Refactoring
      perf: Performance Improvements
      test: Testing
      build: Build System or External Dependencies
      ci: CI Configuration Changes
      chore: Chore
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
