# Pushes Docker images created from the deploy tool's Dockerfile templates to an internal ECR so that they can be scanned for security vulnerabilities.
name: Upload Docker Images

on:
  # Manually trigger on specific branches
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  upload-docker-images:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 #v5.1.1
      with:
        aws-region: us-west-2
        role-to-assume: ${{ secrets.DOCKER_IMAGE_UPLOADER_ROLE }}
        role-duration-seconds: 1800

    - name: Checkout Repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
      with:
        fetch-depth: 0
     
    - name: Setup .NET 8
      uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 #v5.1.0
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run Docker Image Uploader
      run: |
        cd ./test/AWS.Deploy.DockerImageUploader
        dotnet run --project ./AWS.Deploy.DockerImageUploader.csproj
