# Pushes Docker images created from the deploy tool's Dockerfile templates to an internal ECR so that they can be scanned for security vulnerabilities.
name: Upload Docker Images

on:
  # Manually trigger on specific branches
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  upload-docker-images:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@f24d7193d98baebaeacc7e2227925dd47cc267f5 #v4.2.0
      with:
        aws-region: us-west-2
        role-to-assume: ${{ secrets.DOCKER_IMAGE_UPLOADER_ROLE }}
        role-duration-seconds: 1800

    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      with:
        fetch-depth: 0
     
    - name: Setup .NET Core 6.0
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 #v4.3.1
      with:
        dotnet-version: 6.0.x
     
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 #v4.3.1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run Docker Image Uploader
      run: |
        cd ./test/AWS.Deploy.DockerImageUploader
        dotnet run --project ./AWS.Deploy.DockerImageUploader.csproj
